let newProductArray = [
    {
        pid:6,
        pname:'NOVA Modular Sofa',
        pdesc:`낮고 넓은 실루엣의 모듈형 패브릭 소파`,
        price:1890000,
        pdiscount:0.15,
        pthumbFilename:'n-1.jpg',
    },
    {
        pid:7,
        pname:'AERO Lounge Chair',
        pdesc:`곡선형 쉘과 부드러운 쿠션을 결합한 1인 체어`,
        price:649000,
        pdiscount:0,
        pthumbFilename:'n-2.jpg',
    },
    {
        pid:8,
        pname:'ARC Coffee Table',
        pdesc:`둥근 모서리와 묵직한 원통형 베이스가 특징`,
        price:429000,
        pdiscount:0,
        pthumbFilename:'n-3.jpg',
    },
    {
        pid:9,
        pname:'FRAME Dining Table',
        pdesc:`얇은 상판과 독특한 구조의 미니멀 다이닝 테이블`,
        price:879000,
        pdiscount:0,
        pthumbFilename:'n-4.jpg',
    },
    {
        pid:10,
        pname:'FORM Dining Chair',
        pdesc:`등받이와 좌판이 하나로 이어지는 심플한 곡선형 디자인`,
        price:289000,
        pdiscount:0,
        pthumbFilename:'n-5.jpg',
    },
    {
        pid:11,
        pname:'PULSE Side Table',
        pdesc:`작은 원형 상판과 세련된 메탈 프레임`,
        price:249000,
        pdiscount:0,
        pthumbFilename:'n-6.jpg',
    },
    {
        pid:12,
        pname:'LINE Sideboard',
        pdesc:`수평 라인을 강조한 낮고 긴 모던 사이드보드`,
        price:1090000,
        pdiscount:0,
        pthumbFilename:'n-7.jpg',
    },
    {
        pid:13,
        pname:'GRID Shelf',
        pdesc:`정돈된 격자 구조와 비대칭 선반을 활용한 책장`,
        price:699000,
        pdiscount:0,
        pthumbFilename:'n-8.jpg',
    },
    {
        pid:14,
        pname:'FRAME Bed',
        pdesc:`헤드보드와 프레임이 일체형으로 연결된 미니멀 침대`,
        price:1490000,
        pdiscount:0,
        pthumbFilename:'n-9.jpg',
    },
    {
        pid:15,
        pname:'CUBE Bedside Table',
        pdesc:`단순한 직육면체 형태에 간접 수납을 더한 협탁`,
        price:249000,
        pdiscount:0,
        pthumbFilename:'n-10.jpg',
    },
    {
        pid:16,
        pname:'VECTOR Media Console',
        pdesc:`낮고 긴 형태에 슬림한 다리를 적용한 미디어 콘솔`,
        price:899000,
        pdiscount:0,
        pthumbFilename:'n-11.jpg',
    },
    {
        pid:17,
        pname:'ARC Floor Lamp',
        pdesc:`부드럽게 휘어진 메탈 프레임과 간접 조명의 조합`,
        price:329000,
        pdiscount:0,
        pthumbFilename:'n-12.jpg',
    },
    


]
