let productArray = [
    {
        pid:0,
        pname:'LUME Modular Sofa',
        pdesc:`부드러운 곡선과 넉넉한 좌석으로 완성한 모던 모듈러 소파입니다.`,
        price:1290000,
        pdiscount:0.15,
        pdiscountactl:0.75,
        priceDiscount:1096500,
        plikes:6456,
        pthumbFilename:'ss1.jpg',
    },
    {
        pid:1,
        pname:'NOVA Dining Set',
        pdesc:`깔끔한 실루엣과 균형 잡힌 비율이 돋보이는 다이닝 세트입니다.`,
        price:890000,
        pdiscount:0.2,
        pdiscountactl:0.8,
        priceDiscount:712000,
        plikes:4526,
        pthumbFilename:'ss2.jpg',
    },
    {
        pid:2,
        pname:'ELIO Frame Bed',
        pdesc:`절제된 프레임과 부드러운 헤드보드로 편안한 침실을 연출합니다.`,
        price:1090000,
        pdiscount:0.18,
        pdiscountactl:0.88,
        priceDiscount:893800,
        plikes:8313,
        pthumbFilename:'ss3.jpg',
    },
    {
        pid:3,
        pname:'Moss Sideboard',
        pdesc:`절제된 프레임과 부드러운 헤드보드로 편안한 침실을 연출합니다.`,
        price:690000,
        pdiscount:0.15,
        pdiscountactl:0.75,
        priceDiscount:586500,
        plikes:21077,
        pthumbFilename:'ss4.jpg',
    },
    {
        pid:4,
        pname:'FRAME Mini Table',
        pdesc:`거실의 중심을 안정감 있게 잡아주는 미니멀한 디자인입니다.`,
        price:520000,
        pdiscount:0.1,
        pdiscountactl:0.9,
        priceDiscount:468000,
        plikes:6456,
        pthumbFilename:'ss5.jpg',
    },
    {
        pid:5,
        pname:'Moss Minimal Chair',
        pdesc:`편안한 착석감과 차분한 색감으로 휴식의 순간을 더욱 여유롭게 만들어줍니다.`,
        price:390000,
        pdiscount:0.12,
        pdiscountactl:0.88,
        priceDiscount:343200,
        plikes:13462,
        pthumbFilename:'ss6.jpg',
    },
]